---
# tasks file for configure_gandi_dns_records

- name: Delete all Gandi DNS records For the Given Domain
  uri:
    url: "https://{{ api_domain }}/{{ api_version }}/{{ api_endpoint }}/domains/{{ server_domain }}/records"
    method: DELETE
    return_content: yes
    validate_certs: true
    status_code: 204
    timeout: 180
    headers:
      Content-Type: application/json
      Authorization: "Apikey {{ dns_api_key }}"
  when: server_domain is defined

- name: Configure a Gandi DNS Records For the Given Domain
  uri:
    url: "https://{{ api_domain }}/{{ api_version }}/{{ api_endpoint }}/domains/{{ server_domain }}/records"
    method: PUT
    return_content: yes
    body: "{{ lookup('template', dns_template + '.j2') }}"
    validate_certs: true
    status_code: 201
    timeout: 180
    headers:
      Content-Type: application/json
      Authorization: "Apikey {{ dns_api_key }}"
    body_format: json
  when: server_domain is defined