---
# tasks file for configure_gandi_dns_records

- name: Delete all Gandi DNS records For the Given Domain
  uri:
    url: "https://{{ api_domain }}/{{ api_version }}/{{ api_endpoint_livedns }}/domains/{{ server_domain }}/records"
    method: DELETE
    return_content: yes
    validate_certs: true
    status_code: 204
    timeout: 180
    headers:
      Content-Type: application/json
      Authorization: "Apikey {{ dns_api_key }}"
  when: server_domain is defined

- name: Set DNS template variable
  set_fact:
    template: "{{ dns_template | default('default-a', true) }}"

- name: Configure Gandi DNS Records For the Given Domain
  uri:
    url: "https://{{ api_domain }}/{{ api_version }}/{{ api_endpoint_livedns }}/domains/{{ server_domain }}/records"
    method: PUT
    return_content: yes
    body: "{{ lookup('template', template + '.j2') }}"
    validate_certs: true
    status_code: 201
    timeout: 180
    headers:
      Content-Type: application/json
      Authorization: "Apikey {{ dns_api_key }}"
    body_format: json
  when: server_domain is defined and template is defined