galaxy_info:
  author: froyo75
  description: Install and Configure Cobalt Strike server
  company: froyo75
  license: MIT

  min_ansible_version: 2.4

  galaxy_tags:
    - CobaltStrike
    - c2

dependencies: []