galaxy_info:
  author: froyo75
  description: Install and Configure Apache2 Service
  company: froyo75
  license: MIT

  min_ansible_version: 2.4

  galaxy_tags:
    - apache2
    - web

dependencies: []