---
# tasks file for setup_docker_container

- name: Install required packages (using apt tool)
  apt:
    update_cache: yes
    pkg: 
    - rsync
    - tmux
    - screen
    - dnsutils
    state: present
  when:
   - ansible_pkg_mgr == "apt"
  become: yes

- name: Check if a specific Docker folder is defined for the specified host
  local_action: stat path="../Docker/{{ inventory_hostname }}"
  register: docker_folder

- name: Set Docker folder path variable
  set_fact: 
    docker_folder_path: "{% if not docker_folder.stat.exists %}../Docker/{{ docker_app }}/{% else %}../Docker/{{ inventory_hostname }}{% endif %}"

- name: Copy Docker files to the remote host
  copy:
    src: "{{ docker_folder_path }}"
    dest: "/opt/{{ docker_app }}"
  become: yes

- name: Synchronize permissions
  synchronize:
    delete: yes
    src: "{{ docker_folder_path }}/"
    dest: "/opt/{{ docker_app }}/"
    mode: push
    recursive: yes
  become: yes

- name: Build and start the containers
  shell: "cd /opt/{{ docker_app }} && ./{{ docker_startup_script }}"
  when:
   - ansible_distribution == "Debian"
  register: compose
  become: yes

- debug: var=compose.stdout_lines

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  args:
    executable: /bin/bash
  become: yes



