# Install & Configure a new Gophish instance
- hosts: gophish
  gather_facts: true
  vars:
   virtual_host_template: c2proxy-https.j2
   web_service: apache2
   noautostart: true
   docker_app : gophish
   docker_startup_script: startGoPhish.sh
  roles:
    - configure_letsencrypt
    - install_apache2
    - install_redirect_rules
    - install_docker
    - setup_docker_container
