# Install & Configure a new Evilginx instance
- hosts: evilginx
  gather_facts: true
  vars:
   docker_app : evilginx
   docker_startup_script: startEvilGinx.sh
  roles:
    - install_docker
    - setup_docker_container