# Install & Configure a new Gophish instance
- hosts: gophish
  gather_facts: true
  vars:
   docker_app : gophish-evilginx
   docker_startup_script: startGoPhish.sh
  roles:
    - install_docker
    - setup_docker_container
