version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud_server
    restart: always
    depends_on:
      - mariadb
      - redis
    networks:
      - dbnet
      - redisnet
    environment:
      - PUID=1000
      - PGID=1000
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=redis
    healthcheck:
      test: curl -sSf 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./app/nc/html:/var/www/html
      - ./app/nc/custom_apps:/var/www/html/custom_apps
      - ./app/nc/config:/var/www/html/config
      - ./app/nc/data:/var/www/html/data

  mariadb:
    image: mariadb:10.11
    container_name: nextcloud_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - dbnet
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MARIADB_AUTO_UPGRADE=${MARIADB_AUTO_UPGRADE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./app/mariadb:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - redisnet
    volumes:
      - ./app/redis:/data  
      
networks:
  dbnet:
  redisnet: